module.exports = (()=> {
  return {
    SERVER_URL: 'https://potree.ml/api/',
    // SERVER_URL: 'http://localhost:5000/',
    API_GOOGLE_KEYS: "AIzaSyA51p0T7yIJUk_FOXP2ansqHYVMXWqCrIY",
    ESSENCES_FR: ["Acer Miyabei",
                  "Acer freemanii 'Sienna'",
                  "Acer fremanii 'Armstrong Gold",
                  "Acer g. Flame tiges multiples",
                  "Acer grandidentatum",
                  "Acer grandidentatum ' Rocky Mountain Glow'",
                  "Acer griseum",
                  "Acer miyabei Morton",
                  "Acer negundo Baron",
                  "Acer platanoides 'Princeton Gold'",
                  "Acer platanoides Emerald Lustre",
                  "Acer platanoides Jade Glen",
                  "Acer rubrum 'Autumn Flame'",
                  "Acer rubrum 'Bowhall'",
                  "Acer rubrum 'October Glory'",
                  "Acer rubrum Pyramidal",
                  "Acer saccharinum 'Silver Cloud'",
                  "Acer saccharinum Wierie",
                  "Acer saccharum Apollo",
                  "Acer saccharum Legacy",
                  "Acer saccharum Unity",
                  "Acer x 'Pacific Sunset'",
                  "Acer x freemanii 'Armstrong'",
                  "Acer x freemanii 'Autumn Fantasy'",
                  "Acer x freemanii 'Firefall'",
                  "Acer x freemanii 'Scarlet Sentinel'",
                  "Acer x freemanii 'Sienna Glen'",
                  "Acer x freemanii Celebration",
                  "Acer x freemanii Marmo",
                  "Aesculus carnea 'Briotii'",
                  "Aesculus indica",
                  "Aesculus octandra",
                  "Aesculus x carnea",
                  "Aesculus x carnea Fort McNair",
                  "Aesculus x hybrida",
                  "Ailante glanduleux",
                  "Alisier blanc",
                  "Alisier de Suède",
                  "Alnus incana",
                  "Amelanchier arborea",
                  "Amelanchier c. 'Rainbow Pillar' (Glenn Form)",
                  "Amelanchier g. 'Princess Diana'",
                  "Amelanchier laevis",
                  "Amelanchier laevis 'Prince Charles'",
                  "Amelanchier laevis Cumulus",
                  "Amélanchier",
                  "Amélanchier  Robin Hill",
                  "Amélanchier du Canada",
                  "Amélanchier du Canada Ballerina",
                  "Amélanchier glabre Spring Flurry",
                  "Amélanchier à grandes fleurs",
                  "Amélanchier à grandes fleurs Autumn Brillance",
                  "Arbre à gomme",
                  "Aubépine",
                  "Aubépine Washington",
                  "Aubépine crus-galli inerme",
                  "Aubépine mordenensis Snowbird",
                  "Aubépine mordenensis Toba",
                  "Aubépine mordensis",
                  "Aulne",
                  "Aulne glutineux",
                  "Aulne glutineux Imperialis",
                  "Aulne rugueux",
                  "Ballerina Serviceberry",
                  "Betula alba ",
                  "Betula papyrifera 'Renaissance Reflection'",
                  "Betula pendula 'Fastigiata'",
                  "Betula pendula 'Tristis'",
                  "Bouleau",
                  "Bouleau de l'Himalaya",
                  "Bouleau européen",
                  "Bouleau flexible",
                  "Bouleau gris",
                  "Bouleau jaune",
                  "Bouleau noir",
                  "Bouleau noir Heritage",
                  "Bouleau pleureur de Young",
                  "Bouleau pleureur à feuilles laciniées",
                  "Bouleau à feuilles pourpres",
                  "Bouleau à papier",
                  "Caraganier",
                  "Caraganier de Sibérie",
                  "Caraganier de Sibérie Walker",
                  "Caraganier pleureur",
                  "Caryer",
                  "Caryer cordiforme",
                  "Caryer ovale",
                  "Catalpa",
                  "Catalpa de l'Ouest",
                  "Catalpa parasol",
                  "Celtis occidentalis 'Prairie Sentinel'",
                  "Cercidiphyllum",
                  "Cercidiphyllum du Japon",
                  "Cercis canadensis",
                  "Ceriser de l'amur",
                  "Cerisier Stella",
                  "Cerisier aigre",
                  "Cerisier de Pennsylvanie",
                  "Cerisier de Virginie",
                  "Cerisier de Virginie Canada Red",
                  "Cerisier de Virginie Schubert",
                  "Cerisier décoratif Akebono",
                  "Cerisier tardif",
                  "Cerisier à grappes",
                  "Cerisier à grappes Colorata",
                  "Cerisier à grappes Commutata",
                  "Chalef",
                  "Chamaecyparis",
                  "Chamaecyparis jaune",
                  "Charme",
                  "Charme de Caroline",
                  "Charme européen fastigié",
                  "Chicot",
                  "Chicot Prairie Titan",
                  "Chicot du Canada",
                  "Chicot du Canada 'Stately Manor'",
                  "Chêne",
                  "Chêne Kindred Spirit",
                  "Chêne Régal Prince",
                  "Chêne anglais fastigié",
                  "Chêne blanc",
                  "Chêne bleu",
                  "Chêne des marais",
                  "Chêne pédonculé",
                  "Chêne rouge",
                  "Chêne à feuilles de Laurier",
                  "Chêne à gros fruits",
                  "Chêne écarlate",
                  "Cornouiller",
                  "Cornouiller à feuilles alternes",
                  "Crataegus crus-galli",
                  "Crataegus laevigata 'Crimson Cloud'",
                  "Crataegus x oxyacantha Paul Scarlet",
                  "Divers",
                  "Elaeagnus angustifolia 'Velvet Touch'",
                  "Fagus sylvatica 'Dawyck Gold'",
                  "Fagus sylvatica 'Dawyck Purple'",
                  "Fagus sylvatica 'Dawyck'",
                  "Fraxinus angustifolia ssp. oxycarpa",
                  "Fraxinus angustifolia ssp. syriaca",
                  "Fraxinus bungeana",
                  "Fraxinus chinensis ssp. rynchophylla",
                  "Fraxinus excelsior Aurefolia",
                  "Fraxinus longicuspis",
                  "Fraxinus mandshurica",
                  "Fraxinus p. 'subintergerrima'",
                  "Fraxinus pennsylvanica Superform",
                  "Fraxinus quadrangulata",
                  "Fraxinus sogdiana",
                  "Fraxinus velutina",
                  "Frêne",
                  "Frêne d'Amérique",
                  "Frêne d'Amérique Autumn Puple",
                  "Frêne d'Amérique Kleinberg",
                  "Frêne d'Amérique Manitou",
                  "Frêne d'Amérique Northern Blaze",
                  "Frêne d'Amérique Skyline",
                  "Frêne d'Amérique' 'Juglandifolia'",
                  "Frêne d'Europe",
                  "Frêne d'Europe 'Diversifolia'",
                  "Frêne de Pennsylvanie",
                  "Frêne de Pennsylvanie 'Cimmzam' (Cimmaron)",
                  "Frêne de Pennsylvanie Harlequin",
                  "Frêne de Pennsylvanie Marshall Seedless",
                  "Frêne de Pennsylvanie Patmore",
                  "Frêne de Pennsylvanie Prairies Spires",
                  "Frêne de Pennsylvanie Summit",
                  "Frêne de Siebold",
                  "Frêne des Balkans",
                  "Frêne européen 'Doorenbos'",
                  "Frêne européen 'Eureka'",
                  "Frêne européen 'Hessei'",
                  "Frêne européen 'Kimberly'",
                  "Frêne noir",
                  "Frêne noir Fall Gold",
                  "Frêne noir Northern Treasure",
                  "Frêne pubescent",
                  "Frêne rouge 'Acubifolia'",
                  "Frêne rouge 'Warverley'",
                  "Frêne à feuilles étroites 'Raywood'",
                  "Frêne à fleurs",
                  "Fèvier inerme Fairview",
                  "Févier",
                  "Févier 'Northern Acclaim'",
                  "Févier Elegantissima",
                  "Févier Halka",
                  "Févier Imperial",
                  "Févier Moraine",
                  "Févier Rubylace",
                  "Févier Shademaster",
                  "Févier Skyline",
                  "Févier Spectrum",
                  "Févier Sunburst",
                  "Févier d'Amérique",
                  "Févier inerme d'Amérique",
                  "Gainier du Canada 'Forest Pansy'",
                  "Genévrier de Virginie",
                  "Ginkgo",
                  "Ginkgo Fastigiata",
                  "Ginkgo biloba ''Woodstock'' (Emperor TM)",
                  "Ginkgo biloba Magyar",
                  "Ginkgo biloba mâle",
                  "Ginkgo à feuilles bilobées",
                  "Ginkgo à feuilles bilobées Autumn Gold",
                  "Ginkgo à feuilles bilobées Pendula",
                  "Ginkgo à feuilles bilobées Princeton Sentry",
                  "Gleditsia triacanthos 'Street Keeper'",
                  "Gleditsia triacanthos Prairie Silk",
                  "Gymnocladus dioicus 'Espresso'",
                  "Génévrier",
                  "Heptacodium miconioides",
                  "Hêtre",
                  "Hêtre européen",
                  "Hêtre européen 'Red Obelisk'",
                  "Hêtre européen Purpurea Pendula",
                  "Hêtre européen purpurea",
                  "Hêtre à grandes feuilles",
                  "If",
                  "Larix kaempferi 'Blue Rabbit'",
                  "Lilas",
                  "Lilas de Preston",
                  "Lilas japonais",
                  "Lilas japonais Golden Eclipse",
                  "Lilas japonais Ivory Silk",
                  "Liquidambar 'Moraine'",
                  "Liquidambar Worplesdon",
                  "Maackia Starburst",
                  "Maackie de l'Amur",
                  "Magnolia",
                  "Magnolia 'Daybreak'",
                  "Magnolia 'Galaxy'",
                  "Magnolia 'Sunburst'",
                  "Magnolia Goldstar",
                  "Magnolia Leonard Messel",
                  "Magnolia acuminata",
                  "Magnolia de Soulange",
                  "Magnolia kobus",
                  "Magnolia rustica Rubra",
                  "Malus 'Pink Perfection'",
                  "Malus 'Royal Splendor'",
                  "Malus 'White Angel'",
                  "Malus Rudolph",
                  "Malus Scarlet (Brandy Wine)",
                  "Malus Selkirk",
                  "Malus Spring Snow",
                  "Malus Sugar Tyme",
                  "Malus antonovka",
                  "Malus baccata 'Jackii'",
                  "Malus x 'Golden Raindrops'",
                  "Malus x 'Jefspire'",
                  "Malus x 'Liset'",
                  "Malus x 'Purple Wave'",
                  "Malus x 'Red Splendor'",
                  "Malus x 'Royal Raindrops'",
                  "Malus x adstringens 'Durleo' (Gladiator TM)",
                  "Malus x domestica 'Belmac'",
                  "Malus x domestica 'Freedom'",
                  "Marronnier",
                  "Marronnier d'Inde",
                  "Marronnier de Bauman",
                  "Marronnier du Texas",
                  "Marronnier glabre",
                  "Micocoulier",
                  "Micocoulier occidental",
                  "Mélèze",
                  "Mélèze d'Europe",
                  "Mélèze d'Europe pleureur",
                  "Mélèze du Japon",
                  "Mélèze laricin",
                  "Métaséquoia",
                  "Mûrier",
                  "Mûrier blanc",
                  "Mûrier blanc pleureur",
                  "Mûrier rouge",
                  "Nerprun",
                  "Nerprun bourdaine",
                  "Nerprun cathartique",
                  "Noisetier",
                  "Noisetier de Byzance",
                  "Nom français",
                  "Noyer",
                  "Noyer cendré",
                  "Noyer noir",
                  "Noyer royal",
                  "Nyssa sylvatica",
                  "Olivier de Bohème",
                  "Orme",
                  "Orme 'Cathedral'",
                  "Orme Groeneveld",
                  "Orme Homestead",
                  "Orme Morton (Accolade TM)",
                  "Orme Morton red Tip",
                  "Orme Pioneer",
                  "Orme Princeton",
                  "Orme Sapporo Autumn Gold",
                  "Orme Vanguard",
                  "Orme d'Amérique",
                  "Orme d'Amérique Brandon",
                  "Orme de Sibérie",
                  "Orme de Sibérie Park Royal",
                  "Orme de Thomas",
                  "Orme hybride 'Morton Sarlwart' (Commendation TM)",
                  "Orme japonais du prospecteur",
                  "Orme parasol",
                  "Orme rouge",
                  "Orme vendu comme Morton Glossy",
                  "Ostryer de Virginie",
                  "Patten European Pear",
                  "Peuplier",
                  "Peuplier Noir",
                  "Peuplier Prairie Sky",
                  "Peuplier Tower",
                  "Peuplier baumier",
                  "Peuplier blanc",
                  "Peuplier blanc pyramidal",
                  "Peuplier de Caroline",
                  "Peuplier de Caroline Eugenii",
                  "Peuplier de Lombardie",
                  "Peuplier de Simon",
                  "Peuplier de Simon fastigié",
                  "Peuplier de Thebessa",
                  "Peuplier deltoides Siouxland",
                  "Peuplier deltoïde",
                  "Peuplier faux-tremble",
                  "Peuplier faux-tremble Erecta",
                  "Peuplier à grandes dents",
                  "Phellodendron",
                  "Phellodendron His Majesty",
                  "Phellodendron Lavallei Eye Stopper",
                  "Phellodendron de l'Amour",
                  "Phellodendron de l'Amour Macho",
                  "Phellodendron de l'Amour Maelio",
                  "Picea pungens 'Bakeri'",
                  "Picea pungens 'Engelm'",
                  "Pin",
                  "Pin blanc",
                  "Pin blanc 'Fastigiata'",
                  "Pin blanc de Corée",
                  "Pin flexible",
                  "Pin gris",
                  "Pin mugo",
                  "Pin noir d'Autriche",
                  "Pin noir d'Autriche Arnold Sentinel",
                  "Pin parviflora Glauca",
                  "Pin rigide",
                  "Pin rouge",
                  "Pin sylvestre",
                  "Pin sylvestre 'Fastigiata'",
                  "Pinus cembra",
                  "Pinus contorta",
                  "Pinus mugo 'Tannenbaum'",
                  "Platane",
                  "Platane occidental",
                  "Poirier",
                  "Poirier Chantecleer",
                  "Poirier de Chine",
                  "Poirier de Mandchourie Prairie Gem",
                  "Pommetier 'Adams'",
                  "Pommetier Almey",
                  "Pommetier Brandywine®",
                  "Pommetier Centurion®",
                  "Pommetier Dolgo",
                  "Pommetier Erecta",
                  "Pommetier Harvest Gold TM",
                  "Pommetier Hopa",
                  "Pommetier Indian Magic",
                  "Pommetier Indian Summer",
                  "Pommetier Madonna",
                  "Pommetier Makamik",
                  "Pommetier Mandshurica",
                  "Pommetier Maybride",
                  "Pommetier Maypole Colonade",
                  "Pommetier Pink Spires",
                  "Pommetier Prairifire",
                  "Pommetier Profusion",
                  "Pommetier Radiant",
                  "Pommetier Red Jade",
                  "Pommetier Rinki",
                  "Pommetier Robinson",
                  "Pommetier Rosseau",
                  "Pommetier Rosthern",
                  "Pommetier Royalty",
                  "Pommetier Snowcloud",
                  "Pommetier Snowdrift",
                  "Pommetier Strathmore",
                  "Pommetier Thunderchild",
                  "Pommetier White Splendor",
                  "Pommetier Winter Gold",
                  "Pommetier colonnaire 'DreamWeaver'",
                  "Pommetier de Bechtel",
                  "Pommetier de Sibérie",
                  "Pommetier de Sibérie colonnaire",
                  "Pommetier de Sibérie erecta",
                  "Pommetier de l'Iowa",
                  "Pommetier odorant",
                  "Pommier",
                  "Pommier Empire",
                  "Populus alba 'Bolleana'",
                  "Populus alba 'Nivea'",
                  "Populus sp.(hybrides)",
                  "Populus x canadensis 'Aurea'",
                  "Populus x canadensis 'Erecta'",
                  "Populus x canadensis 'Serotina'",
                  "Pruche de l'Est",
                  "Prunier 'Mont-Royal'",
                  "Prunier d'Amérique",
                  "Prunier domestique",
                  "Prunier noir",
                  "Prunier, Cerisier ou Pêcher",
                  "Prunus cerasifera 'Newport'",
                  "Prunus maakii 'Jefree'",
                  "Prunus maakii 'Jefspur'",
                  "Prunus padus 'Skinner's Red'",
                  "Prunus x cistena",
                  "Pyrus calleryana 'Autumn Blaze'",
                  "Pyrus communis 'Savignac'",
                  "Pyrus ussuriensis",
                  "Pyrus ussuriensis 'Mountain Frost'",
                  "Pêcher",
                  "Quercus ellipsoidalis",
                  "Quercus muehlenbergii",
                  "Quercus palustris Green Pillar",
                  "Quercus robur 'Crimson Spire'",
                  "Robinia pseudoacacia 'Twisty Baby'",
                  "Robinia pseudoacacia Purple Robe",
                  "Robinier",
                  "Robinier faux-acacia",
                  "Robinier faux-acacia Frisia",
                  "Salix babylonica 'Crispa'",
                  "Salix x chrysocoma",
                  "Sapin",
                  "Sapin argenté",
                  "Sapin baumier",
                  "Sapin de Douglas",
                  "Sapin de Douglas bleu",
                  "Saule",
                  "Saule Prairie Cascade",
                  "Saule blanc",
                  "Saule de Pékin",
                  "Saule laurier",
                  "Saule noir",
                  "Saule osier jaune",
                  "Saule pleureur",
                  "Saule tortueux de Pékin",
                  "Sorbier",
                  "Sorbier d'Amérique",
                  "Sorbier de Corée",
                  "Sorbier des montagnes",
                  "Sorbier des oiseaux",
                  "Sorbier des oiseaux Cardinal Royal",
                  "Sorbier des oiseaux Rosedale",
                  "Sorbier des oiseaux Rossica",
                  "Sorbier des oiseaux fastigié",
                  "Sorbier à feuilles de chêne",
                  "Sorbier à feuilles de chêne fastigié",
                  "Sorbus xanthocarpa",
                  "Sumac",
                  "Syringa vulgaris",
                  "Taxus cuspidata Capitata",
                  "Thuya",
                  "Thuya occidental",
                  "Thuya occidental Nigra",
                  "Thuya occidental Smaragd",
                  "Thuya occidental Spiralis",
                  "Thuya occidental Sunkist",
                  "Thuya occidental fastigié",
                  "Thuya occidental pyramidal",
                  "Thuya occidentalis 'Wareana'",
                  "Tilia a. Lincoln",
                  "Tilia cordata 'De Groot'",
                  "Tilia cordata 'Green Globe'",
                  "Tilia tomentosa 'Brabant'",
                  "Tilia x europea 'Euchlora'",
                  "Tilleul",
                  "Tilleul américain Duros (True North TM)",
                  "Tilleul argenté",
                  "Tilleul argenté Satin Shadow",
                  "Tilleul argenté Sterling",
                  "Tilleul d'Amérique",
                  "Tilleul d'Amérique Boulevard",
                  "Tilleul d'Amérique Redmond",
                  "Tilleul d'Europe",
                  "Tilleul de Mongolie",
                  "Tilleul de Mongolie Harvest Gold",
                  "Tilleul de Varsovie",
                  "Tilleul européen Summer Sprite",
                  "Tilleul à petites feuilles",
                  "Tilleul à petites feuilles 'Ronald'",
                  "Tilleul à petites feuilles Corinthien",
                  "Tilleul à petites feuilles Glenleven",
                  "Tilleul à petites feuilles Greenspire",
                  "Tilleul à petites feuilles Morden",
                  "Tilleul à petites feuilles Shamrock",
                  "Tilleul à petites feuilles Sheridan",
                  "Tremble européen colonnaire",
                  "Tulipier de Virginie",
                  "Ulmus  Valley Forge",
                  "Ulmus americana New Harmony",
                  "Ulmus glabra 'Pendula'",
                  "Ulmus parvifolia",
                  "Ulmus propinqua 'Emerald Sunhine' TM",
                  "Ulmus x 'Frontier'",
                  "Ulmus x 'Morton Glossy' (Triumph TM)",
                  "Ulmus x New Horizon",
                  "Ulmus x Patriots",
                  "Vinaigrier",
                  "Virgilier",
                  "Virgilier à bois jaune",
                  "Virgilier, Virgilier à bois jaune",
                  "Zelkova",
                  "Zelkova du Japon",
                  "Zelkova du Japon Green Vase",
                  "arbre de Katsura Red Fox",
                  "fèvier True Shade",
                  "micocoulier Prairie Pride",
                  "peuplier",
                  "sapin de Corée",
                  "thuyas",
                  "Épinette",
                  "Épinette blanche",
                  "Épinette blanche pleureuse",
                  "Épinette bleu du Colorado",
                  "Épinette de Norvège",
                  "Épinette de Norvège Cupressina",
                  "Épinette de Serbie",
                  "Épinette du Colorado",
                  "Épinette du Colorado Fat Albert",
                  "Épinette du Colorado Glauca",
                  "Épinette du Colorado Hoopsii",
                  "Épinette du Colorado Koster",
                  "Épinette du Colorado pleureuse",
                  "Épinette noire",
                  "Épinette rouge",
                  "Érable",
                  "Érable Autumn Blaze",
                  "Érable argenté",
                  "Érable argenté 'Montréal'",
                  "Érable argenté Pyramidal",
                  "Érable argenté Silver Queen",
                  "Érable argenté à feuilles laciniées",
                  "Érable champêtre",
                  "Érable de Freeman",
                  "Érable de Norvège",
                  "Érable de Norvège Alberta Park",
                  "Érable de Norvège Cleveland",
                  "Érable de Norvège Crimson King",
                  "Érable de Norvège Crimson Sentry",
                  "Érable de Norvège Deborah",
                  "Érable de Norvège Emerald Queen",
                  "Érable de Norvège Fairview",
                  "Érable de Norvège Parkway",
                  "Érable de Norvège Royal Red",
                  "Érable de Norvège Schwedleri",
                  "Érable de Norvège Summershade",
                  "Érable de Norvège Superform",
                  "Érable de Norvège colonnaire",
                  "Érable de Norvège globe",
                  "Érable de Norvège panaché",
                  "Érable de Pennsylvanie",
                  "Érable de Tartarie",
                  "Érable de l'Amur Beethoven",
                  "Érable de l'Armour",
                  "Érable de l'Armour Flame",
                  "Érable du Japon",
                  "Érable noir",
                  "Érable noir Green Column",
                  "Érable rouge",
                  "Érable rouge Armstrong",
                  "Érable rouge Karpick",
                  "Érable rouge Morgan",
                  "Érable rouge Northwood",
                  "Érable rouge Red Sunset",
                  "Érable rouge Supersonic",
                  "Érable rouge colonnaire",
                  "Érable sycamore",
                  "Érable sycomore Regal Petticoat",
                  "Érable truncatum",
                  "Érable à Giguère",
                  "Érable à Giguère panaché",
                  "Érable à sucre",
                  "Érable à sucre 'Bonfire'",
                  "Érable à sucre 'Green Mountain'",
                  "Érable à sucre Commemoration",
                  "Érable à sucre Fall Fiesta",
                  "Érable à sucre Temple Upright",
                  "Érable à épis",
                  "épinette",
                  "épinette bleu Colson's Select Blue",
                  "érable Armstong Gold",
                  "érable de Tartarie 'GarAnn' (Hot Wings TM)",
                  "érable ginnala Ruby Slippers",
                  "érable rouge Autumn Radiance",
                  "érable rouge Brandywine",
                  "érable rouge Red Rocket",
                  "érable rouge Redpointe",
                  "érable rouge fastigié",
                  "érable à sucre  Endowment"]
  }
})()
